- wget -S -a .LOG to keep headers etc - fixed that reload didn't display (delay so the .TMP gets created meanwhile)

diff --git a/wdownload b/wdownload
--- a/wdownload
+++ b/wdownload
@@ -29,7 +29,8 @@ CFILE=$WDIR/Cache/$SAFE
 [ $DOWNLOAD ] && ( \
   echo "`date --iso=s` #=W $GO $CFILE.ANSI" \
     | tee -a .wlog \
-    | tee -a $CFILE.WLOG )
+    | tee -a $CFILE.WLOG ) \
+  > /dev/null
     
 # TODO: it's now done in wless.c
 # but it would be nice to have this one to 
@@ -80,7 +81,7 @@ if [[ ! -f "$CFILE.DOWN" ]]; then
    # - download
    # (.TMP indicates download started)
 
-  (wget -O $CFILE.TMP "$GO" || echo 0 ) 2>&1 | grep ERROR > $CFILE.ERR \
+  (wget -S -a $CFILE.LOG -O $CFILE.TMP "$GO" || echo 0 ) 2>&1 | grep ERROR > $CFILE.ERR \
     && (err=$? ; echo "WGET.ERROR $?" >> $CFILE.ERR ; exit $err) \
    && rm $CFILE.TMP || rm $CFILE.ERR
 
